; SIDEY-specific strings. Standard wizard buttons/pages come from NSIS's NLF files.
LangString LanguageSelectionFailed ${LANG_ENGLISH} "The language selection window could not be opened. Run Setup again."
LangString LanguageSelectionFailed ${LANG_KOREAN} "언어 선택 창을 열지 못했습니다. 설치 프로그램을 다시 실행해 주세요."
LangString LanguageSelectionFailed ${LANG_JAPANESE} "言語選択画面を開けませんでした。セットアップを再実行してください。"
LangString LanguageSelectionFailed ${LANG_SIMPCHINESE} "无法打开语言选择窗口。请重新运行安装程序。"
LangString LanguageSelectionFailed ${LANG_TRADCHINESE} "無法開啟語言選擇視窗。請重新執行安裝程式。"
LangString LanguageSelectionFailed ${LANG_RUSSIAN} "Не удалось открыть окно выбора языка. Запустите программу установки ещё раз."
LangString LanguageSelectionFailed ${LANG_UKRAINIAN} "Не вдалося відкрити вікно вибору мови. Запустіть програму встановлення ще раз."

LangString LaunchSidey ${LANG_JAPANESE} "SIDEY を起動する"
LangString TermsTitle ${LANG_JAPANESE} "SIDEY 利用規約"
LangString TermsSubtitle ${LANG_JAPANESE} "インストールする前に、利用規約を確認して同意してください。"
LangString TermsTop ${LANG_JAPANESE} "以下の利用規約をお読みください。続行するには同意のチェックボックスを選択してください。"
LangString AcceptTerms ${LANG_JAPANESE} "SIDEY の利用規約を読み、同意します。"
LangString MaintenanceTitle ${LANG_JAPANESE} "SIDEY は既にインストールされています"
LangString MaintenanceSubtitle ${LANG_JAPANESE} "実行する操作を選択してください。"
LangString MaintenanceDescription ${LANG_JAPANESE} "同じバージョンの SIDEY がインストールされています。修復またはアンインストールを選択できます。"
LangString RepairAction ${LANG_JAPANESE} "修復"
LangString RemoveAction ${LANG_JAPANESE} "アンインストール"
LangString CloseAction ${LANG_JAPANESE} "閉じる"
LangString DowngradeBlocked ${LANG_JAPANESE} "新しいバージョンの SIDEY が既にインストールされているため、変更は行われませんでした。${APP_VERSION} をインストールするには、Windows の設定 > アプリから現在の SIDEY をアンインストールし、このセットアップを再実行してください。"
LangString LegacyMigrationManual ${LANG_JAPANESE} "以前の SIDEY MSI がインストールされているため、変更は行われませんでした。Windows の設定 > アプリからアンインストールし、このセットアップを再実行してください。SIDEY のインストールファイルを手動で削除しないでください。"
LangString ExistingRemovalFailed ${LANG_JAPANESE} "必要な SIDEY のインストールファイルが見つからないか使用中の可能性があるため、既存のアンインストーラーを完了できませんでした。このセットアップを再実行して修復を完了し、もう一度セットアップを実行してアンインストールを選んでください。修復に失敗した場合は Windows を再起動してもう一度お試しください。それでも解決しない場合は、エラーコード $0 を添えてサポートにお問い合わせください。"
LangString PrerequisitesStatus ${LANG_JAPANESE} "必要なランタイムを確認しています。不足している場合は Microsoft からダウンロードします..."
LangString CleanupTitle ${LANG_JAPANESE} "SIDEY のユーザーデータの削除"
LangString CleanupSubtitle ${LANG_JAPANESE} "削除する現在のユーザーのデータを選択してください。"
LangString CleanupDescription ${LANG_JAPANESE} "SIDEY アプリをアンインストールします。以下のデータは、選択しない限り保持されます。"
LangString DeleteLocalData ${LANG_JAPANESE} "設定とログを削除する (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_JAPANESE} "保存された SIDEY のログイン情報を削除する"
LangString CleanupFailed ${LANG_JAPANESE} "SIDEY の削除は続行しますが、次の現在のユーザーの項目を削除できませんでした。表示されたエラーコードは各項目のものです:$\r$\n$CleanupFailureDetails"
LangString CleanupLocalDataFailure ${LANG_JAPANESE} "- 設定とログ (%LOCALAPPDATA%\SIDEY)、エラーコード: $0"
LangString CleanupCredentialsFailure ${LANG_JAPANESE} "- 保存された SIDEY のログイン情報、エラーコード: $0"
LangString CleanupStartupFailure ${LANG_JAPANESE} "- SIDEY のスタートアップ項目、エラーコード: $0"
LangString LaunchFailed ${LANG_JAPANESE} "SIDEY のインストールは完了しましたが、デスクトップユーザーとして起動できませんでした。Windows を再起動し、スタートメニューから SIDEY を起動してください。それでも起動しない場合は、エラーコード $0 を添えてサポートにお問い合わせください。"
LangString TransactionFailed ${LANG_JAPANESE} "SIDEY のインストールを完了できませんでした。SIDEY が既にインストールされていた場合、以前のインストールは保持または復元されました。エラーコード: $0"
LangString TransactionStateUnknown ${LANG_JAPANESE} "SIDEY の最終的なインストール状態を確認できませんでした。Windows を再起動し、最新の SIDEY セットアップを再実行してください。修復が表示された場合は完了してください。インストールファイルを手動で削除しないでください。続行できない場合は、エラーコード $0 を添えてサポートにお問い合わせください。"
LangString TransactionRecoveryFailed ${LANG_JAPANESE} "中断された SIDEY のインストールを復旧できませんでした。Windows を再起動し、最新の SIDEY セットアップをもう一度実行してください。インストールファイルを手動で削除しないでください。問題が続く場合は、エラーコード $0 を添えてサポートにお問い合わせください。"
LangString UninstallPreflightFailed ${LANG_JAPANESE} "SIDEY の削除準備ができなかったため、アンインストールの変更は開始されませんでした。SIDEY を終了し、Windows を再起動してからもう一度お試しください。問題が続く場合は、エラーコード $0 を添えてサポートにお問い合わせください。"
LangString UninstallStateUnknown ${LANG_JAPANESE} "SIDEY の最終的な削除状態を確認できませんでした。Windows を再起動し、最新の SIDEY セットアップをもう一度実行してください。インストールファイルを手動で削除しないでください。問題が続く場合は、エラーコード $0 を添えてサポートにお問い合わせください。"
LangString SetupAlreadyRunning ${LANG_JAPANESE} "別の SIDEY セットアップまたはアンインストーラーが実行中です。終了してから続行してください。"
LangString SetupInitializationFailed ${LANG_JAPANESE} "SIDEY セットアップでインストールロックを初期化できませんでした。Windows を再起動し、セットアップをもう一度実行してください。問題が続く場合は、エラーコード $1 を添えてサポートにお問い合わせください。"
LangString CleanupPending ${LANG_JAPANESE} "SIDEY はインストールされましたが、以前のバージョンのバックアップを削除できませんでした。次回のセットアップで再試行します。"

LangString LaunchSidey ${LANG_SIMPCHINESE} "启动 SIDEY"
LangString TermsTitle ${LANG_SIMPCHINESE} "SIDEY 使用条款"
LangString TermsSubtitle ${LANG_SIMPCHINESE} "安装 SIDEY 前，请阅读并同意使用条款。"
LangString TermsTop ${LANG_SIMPCHINESE} "请阅读以下条款。勾选同意复选框后才能继续。"
LangString AcceptTerms ${LANG_SIMPCHINESE} "我已阅读并同意 SIDEY 使用条款。"
LangString MaintenanceTitle ${LANG_SIMPCHINESE} "已安装 SIDEY"
LangString MaintenanceSubtitle ${LANG_SIMPCHINESE} "请选择要执行的操作。"
LangString MaintenanceDescription ${LANG_SIMPCHINESE} "已安装相同版本的 SIDEY。您可以修复安装或卸载 SIDEY。"
LangString RepairAction ${LANG_SIMPCHINESE} "修复"
LangString RemoveAction ${LANG_SIMPCHINESE} "卸载"
LangString CloseAction ${LANG_SIMPCHINESE} "关闭"
LangString DowngradeBlocked ${LANG_SIMPCHINESE} "已安装更新版本的 SIDEY，因此安装程序未进行任何更改。要安装 ${APP_VERSION}，请从 Windows 设置 > 应用中卸载当前 SIDEY，然后重新运行此安装程序。"
LangString LegacyMigrationManual ${LANG_SIMPCHINESE} "检测到旧版 SIDEY MSI，因此安装程序未进行任何更改。请从 Windows 设置 > 应用中卸载该版本，然后重新运行此安装程序。请勿手动删除 SIDEY 安装文件。"
LangString ExistingRemovalFailed ${LANG_SIMPCHINESE} "所需的 SIDEY 安装文件可能丢失或正在使用，因此现有卸载程序无法完成。请重新运行此安装程序并完成修复，然后再次运行并选择卸载。如果修复失败，请重启 Windows 后再试一次。如果问题仍然存在，请联系支持人员并提供错误代码：$0"
LangString PrerequisitesStatus ${LANG_SIMPCHINESE} "正在检查所需的运行时；缺少的运行时将从 Microsoft 下载..."
LangString CleanupTitle ${LANG_SIMPCHINESE} "选择要删除的 SIDEY 用户数据"
LangString CleanupSubtitle ${LANG_SIMPCHINESE} "请选择要删除的当前用户数据。"
LangString CleanupDescription ${LANG_SIMPCHINESE} "SIDEY 应用将被卸载。以下数据仅在勾选后才会删除。"
LangString DeleteLocalData ${LANG_SIMPCHINESE} "删除设置和日志 (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_SIMPCHINESE} "删除已保存的 SIDEY 登录凭据"
LangString CleanupFailed ${LANG_SIMPCHINESE} "SIDEY 将继续卸载，但无法删除以下当前用户项目。列出的错误代码属于对应项目：$\r$\n$CleanupFailureDetails"
LangString CleanupLocalDataFailure ${LANG_SIMPCHINESE} "- 设置和日志 (%LOCALAPPDATA%\SIDEY)，错误代码：$0"
LangString CleanupCredentialsFailure ${LANG_SIMPCHINESE} "- 已保存的 SIDEY 登录凭据，错误代码：$0"
LangString CleanupStartupFailure ${LANG_SIMPCHINESE} "- SIDEY 启动项，错误代码：$0"
LangString LaunchFailed ${LANG_SIMPCHINESE} "SIDEY 已成功安装，但无法以桌面用户身份启动。请重启 Windows，然后从开始菜单启动 SIDEY。如果仍无法启动，请联系客户支持并提供错误代码：$0"
LangString TransactionFailed ${LANG_SIMPCHINESE} "SIDEY 安装未完成。如果之前已安装 SIDEY，则先前的安装已保留或恢复。错误代码：$0"
LangString TransactionStateUnknown ${LANG_SIMPCHINESE} "安装程序无法确认 SIDEY 的最终安装状态。请重启 Windows，然后再次运行最新的 SIDEY 安装程序。如果安装程序提供修复，请完成修复。请勿手动删除安装文件。如果无法继续，请联系客户支持并提供错误代码：$0"
LangString TransactionRecoveryFailed ${LANG_SIMPCHINESE} "安装程序无法恢复中断的 SIDEY 安装。请重启 Windows，然后再次运行最新的 SIDEY 安装程序。请勿手动删除安装文件。如果问题仍然存在，请联系客户支持并提供错误代码：$0"
LangString UninstallPreflightFailed ${LANG_SIMPCHINESE} "SIDEY 无法准备卸载，因此尚未进行卸载更改。请关闭 SIDEY，重启 Windows 后重试。如果问题仍然存在，请联系客户支持并提供错误代码：$0"
LangString UninstallStateUnknown ${LANG_SIMPCHINESE} "安装程序无法确认 SIDEY 的最终卸载状态。请重启 Windows，然后再次运行最新的 SIDEY 安装程序。请勿手动删除安装文件。如果问题仍然存在，请联系客户支持并提供错误代码：$0"
LangString SetupAlreadyRunning ${LANG_SIMPCHINESE} "另一个 SIDEY 安装程序或卸载程序正在运行。请先将其关闭。"
LangString SetupInitializationFailed ${LANG_SIMPCHINESE} "SIDEY 安装程序无法初始化安装锁。请重启 Windows，然后再次运行安装程序。如果问题仍然存在，请联系客户支持并提供错误代码：$1"
LangString CleanupPending ${LANG_SIMPCHINESE} "SIDEY 已安装，但无法删除旧版本备份。下次运行安装程序时会重试清理。"

LangString LaunchSidey ${LANG_TRADCHINESE} "啟動 SIDEY"
LangString TermsTitle ${LANG_TRADCHINESE} "SIDEY 使用條款"
LangString TermsSubtitle ${LANG_TRADCHINESE} "安裝 SIDEY 前，請閱讀並同意使用條款。"
LangString TermsTop ${LANG_TRADCHINESE} "請閱讀以下條款。勾選同意核取方塊後才能繼續。"
LangString AcceptTerms ${LANG_TRADCHINESE} "我已閱讀並同意 SIDEY 使用條款。"
LangString MaintenanceTitle ${LANG_TRADCHINESE} "已安裝 SIDEY"
LangString MaintenanceSubtitle ${LANG_TRADCHINESE} "請選擇要執行的操作。"
LangString MaintenanceDescription ${LANG_TRADCHINESE} "已安裝相同版本的 SIDEY。您可以修復安裝或解除安裝 SIDEY。"
LangString RepairAction ${LANG_TRADCHINESE} "修復"
LangString RemoveAction ${LANG_TRADCHINESE} "解除安裝"
LangString CloseAction ${LANG_TRADCHINESE} "關閉"
LangString DowngradeBlocked ${LANG_TRADCHINESE} "已安裝較新版本的 SIDEY，因此安裝程式未進行任何變更。若要安裝 ${APP_VERSION}，請從 Windows 設定 > 應用程式解除安裝目前的 SIDEY，然後重新執行此安裝程式。"
LangString LegacyMigrationManual ${LANG_TRADCHINESE} "偵測到舊版 SIDEY MSI，因此安裝程式未進行任何變更。請從 Windows 設定 > 應用程式解除安裝該版本，然後重新執行此安裝程式。請勿手動刪除 SIDEY 安裝檔案。"
LangString ExistingRemovalFailed ${LANG_TRADCHINESE} "所需的 SIDEY 安裝檔案可能遺失或正在使用，因此現有解除安裝程式無法完成。請重新執行此安裝程式並完成修復，然後再次執行並選擇解除安裝。如果修復失敗，請重新啟動 Windows 後再試一次。如果問題仍然存在，請聯絡支援人員並提供錯誤代碼：$0"
LangString PrerequisitesStatus ${LANG_TRADCHINESE} "正在檢查所需的執行階段；缺少的執行階段將從 Microsoft 下載..."
LangString CleanupTitle ${LANG_TRADCHINESE} "選擇要刪除的 SIDEY 使用者資料"
LangString CleanupSubtitle ${LANG_TRADCHINESE} "請選擇要刪除的目前使用者資料。"
LangString CleanupDescription ${LANG_TRADCHINESE} "SIDEY 應用程式將被解除安裝。以下資料只有在勾選後才會刪除。"
LangString DeleteLocalData ${LANG_TRADCHINESE} "刪除設定和記錄 (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_TRADCHINESE} "刪除已儲存的 SIDEY 登入認證"
LangString CleanupFailed ${LANG_TRADCHINESE} "SIDEY 將繼續解除安裝，但無法刪除以下目前使用者項目。列出的錯誤代碼屬於對應項目：$\r$\n$CleanupFailureDetails"
LangString CleanupLocalDataFailure ${LANG_TRADCHINESE} "- 設定和記錄 (%LOCALAPPDATA%\SIDEY)，錯誤代碼：$0"
LangString CleanupCredentialsFailure ${LANG_TRADCHINESE} "- 已儲存的 SIDEY 登入認證，錯誤代碼：$0"
LangString CleanupStartupFailure ${LANG_TRADCHINESE} "- SIDEY 啟動項目，錯誤代碼：$0"
LangString LaunchFailed ${LANG_TRADCHINESE} "SIDEY 已成功安裝，但無法以桌面使用者身分啟動。請重新啟動 Windows，然後從開始功能表啟動 SIDEY。若仍無法啟動，請聯絡客戶支援並提供錯誤代碼：$0"
LangString TransactionFailed ${LANG_TRADCHINESE} "SIDEY 安裝未完成。如果先前已安裝 SIDEY，先前的安裝已保留或還原。錯誤代碼：$0"
LangString TransactionStateUnknown ${LANG_TRADCHINESE} "安裝程式無法確認 SIDEY 的最終安裝狀態。請重新啟動 Windows，然後再次執行最新的 SIDEY 安裝程式。若安裝程式提供修復，請完成修復。請勿手動刪除安裝檔案。若無法繼續，請聯絡客戶支援並提供錯誤代碼：$0"
LangString TransactionRecoveryFailed ${LANG_TRADCHINESE} "安裝程式無法復原中斷的 SIDEY 安裝。請重新啟動 Windows，然後再次執行最新的 SIDEY 安裝程式。請勿手動刪除安裝檔案。若問題持續，請聯絡客戶支援並提供錯誤代碼：$0"
LangString UninstallPreflightFailed ${LANG_TRADCHINESE} "SIDEY 無法準備解除安裝，因此尚未進行解除安裝變更。請關閉 SIDEY，重新啟動 Windows 後再試一次。若問題持續，請聯絡客戶支援並提供錯誤代碼：$0"
LangString UninstallStateUnknown ${LANG_TRADCHINESE} "安裝程式無法確認 SIDEY 的最終解除安裝狀態。請重新啟動 Windows，然後再次執行最新的 SIDEY 安裝程式。請勿手動刪除安裝檔案。若問題持續，請聯絡客戶支援並提供錯誤代碼：$0"
LangString SetupAlreadyRunning ${LANG_TRADCHINESE} "另一個 SIDEY 安裝程式或解除安裝程式正在執行。請先將其關閉。"
LangString SetupInitializationFailed ${LANG_TRADCHINESE} "SIDEY 安裝程式無法初始化安裝鎖定。請重新啟動 Windows，然後再次執行安裝程式。若問題持續，請聯絡客戶支援並提供錯誤代碼：$1"
LangString CleanupPending ${LANG_TRADCHINESE} "SIDEY 已安裝，但無法刪除舊版本備份。下次執行安裝程式時會重試清理。"

LangString LaunchSidey ${LANG_RUSSIAN} "Запустить SIDEY"
LangString TermsTitle ${LANG_RUSSIAN} "Условия использования SIDEY"
LangString TermsSubtitle ${LANG_RUSSIAN} "Перед установкой ознакомьтесь с условиями и примите их."
LangString TermsTop ${LANG_RUSSIAN} "Прочитайте условия ниже. Чтобы продолжить, установите флажок согласия."
LangString AcceptTerms ${LANG_RUSSIAN} "Я прочитал(а) и принимаю условия использования SIDEY."
LangString MaintenanceTitle ${LANG_RUSSIAN} "SIDEY уже установлен"
LangString MaintenanceSubtitle ${LANG_RUSSIAN} "Выберите нужное действие."
LangString MaintenanceDescription ${LANG_RUSSIAN} "Эта версия SIDEY уже установлена. Вы можете восстановить или удалить приложение."
LangString RepairAction ${LANG_RUSSIAN} "Восстановить"
LangString RemoveAction ${LANG_RUSSIAN} "Удалить"
LangString CloseAction ${LANG_RUSSIAN} "Закрыть"
LangString DowngradeBlocked ${LANG_RUSSIAN} "Уже установлена более новая версия SIDEY, поэтому установщик ничего не изменил. Чтобы установить ${APP_VERSION}, удалите текущую версию SIDEY в Параметры Windows > Приложения, затем снова запустите этот установщик."
LangString LegacyMigrationManual ${LANG_RUSSIAN} "Установлена предыдущая MSI-версия SIDEY, поэтому установщик ничего не изменил. Удалите её в Параметры Windows > Приложения, затем снова запустите этот установщик. Не удаляйте файлы установки SIDEY вручную."
LangString ExistingRemovalFailed ${LANG_RUSSIAN} "Программа удаления не завершила работу: необходимые файлы SIDEY могут отсутствовать или использоваться. Снова запустите эту программу установки и выполните восстановление, затем запустите её ещё раз и выберите удаление. Если восстановление завершится ошибкой, перезапустите Windows и повторите попытку. Если проблема останется, обратитесь в поддержку и укажите код ошибки: $0"
LangString PrerequisitesStatus ${LANG_RUSSIAN} "Проверка необходимых сред выполнения. Недостающие компоненты будут загружены с сайта Microsoft..."
LangString CleanupTitle ${LANG_RUSSIAN} "Удаление пользовательских данных SIDEY"
LangString CleanupSubtitle ${LANG_RUSSIAN} "Выберите данные текущего пользователя для удаления."
LangString CleanupDescription ${LANG_RUSSIAN} "Приложение SIDEY будет удалено. Данные ниже сохранятся, если не отметить их для удаления."
LangString DeleteLocalData ${LANG_RUSSIAN} "Удалить настройки и журналы (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_RUSSIAN} "Удалить сохранённые учётные данные для входа в SIDEY"
LangString CleanupFailed ${LANG_RUSSIAN} "Удаление SIDEY продолжится, но следующие элементы текущего пользователя удалить не удалось. Указанный код ошибки относится к соответствующему элементу:$\r$\n$CleanupFailureDetails"
LangString CleanupLocalDataFailure ${LANG_RUSSIAN} "- Настройки и журналы (%LOCALAPPDATA%\SIDEY), код ошибки: $0"
LangString CleanupCredentialsFailure ${LANG_RUSSIAN} "- Сохранённые учётные данные для входа в SIDEY, код ошибки: $0"
LangString CleanupStartupFailure ${LANG_RUSSIAN} "- Запись автозапуска SIDEY, код ошибки: $0"
LangString LaunchFailed ${LANG_RUSSIAN} "SIDEY успешно установлен, но его не удалось запустить от имени пользователя рабочего стола. Перезапустите Windows и запустите SIDEY из меню «Пуск». Если SIDEY по-прежнему не запускается, обратитесь в службу поддержки и укажите код ошибки: $0"
LangString TransactionFailed ${LANG_RUSSIAN} "Установка SIDEY не завершена. Если SIDEY уже был установлен, предыдущая установка сохранена или восстановлена. Код ошибки: $0"
LangString TransactionStateUnknown ${LANG_RUSSIAN} "Установщик не смог подтвердить итоговое состояние SIDEY. Перезапустите Windows и снова запустите последнюю версию установщика SIDEY. Если установщик предложит восстановление, завершите его. Не удаляйте файлы установки вручную. Если продолжить невозможно, обратитесь в службу поддержки и укажите код ошибки: $0"
LangString TransactionRecoveryFailed ${LANG_RUSSIAN} "Установщику не удалось восстановить прерванную установку SIDEY. Перезапустите Windows, затем снова запустите последнюю версию установщика SIDEY. Не удаляйте файлы установки вручную. Если проблема сохранится, обратитесь в службу поддержки и укажите код ошибки: $0"
LangString UninstallPreflightFailed ${LANG_RUSSIAN} "Не удалось подготовить удаление SIDEY, поэтому изменения удаления не были начаты. Закройте SIDEY, перезапустите Windows и повторите попытку. Если проблема сохранится, обратитесь в службу поддержки и укажите код ошибки: $0"
LangString UninstallStateUnknown ${LANG_RUSSIAN} "Установщик не смог подтвердить итоговое состояние удаления SIDEY. Перезапустите Windows, затем снова запустите последнюю версию установщика SIDEY. Не удаляйте файлы установки вручную. Если проблема сохранится, обратитесь в службу поддержки и укажите код ошибки: $0"
LangString SetupAlreadyRunning ${LANG_RUSSIAN} "Другая программа установки или удаления SIDEY уже запущена. Закройте её перед продолжением."
LangString SetupInitializationFailed ${LANG_RUSSIAN} "Установщику SIDEY не удалось инициализировать блокировку установки. Перезапустите Windows и снова запустите установщик. Если проблема сохранится, обратитесь в службу поддержки и укажите код ошибки: $1"
LangString CleanupPending ${LANG_RUSSIAN} "SIDEY установлена, но резервную копию предыдущей версии удалить не удалось. Очистка будет повторена при следующем запуске установки."

LangString LaunchSidey ${LANG_UKRAINIAN} "Запустити SIDEY"
LangString TermsTitle ${LANG_UKRAINIAN} "Умови використання SIDEY"
LangString TermsSubtitle ${LANG_UKRAINIAN} "Перед встановленням ознайомтеся з умовами та прийміть їх."
LangString TermsTop ${LANG_UKRAINIAN} "Прочитайте умови нижче. Щоб продовжити, установіть прапорець згоди."
LangString AcceptTerms ${LANG_UKRAINIAN} "Я прочитав(-ла) та приймаю умови використання SIDEY."
LangString MaintenanceTitle ${LANG_UKRAINIAN} "SIDEY уже встановлено"
LangString MaintenanceSubtitle ${LANG_UKRAINIAN} "Виберіть потрібну дію."
LangString MaintenanceDescription ${LANG_UKRAINIAN} "Цю версію SIDEY уже встановлено. Ви можете відновити або видалити застосунок."
LangString RepairAction ${LANG_UKRAINIAN} "Відновити"
LangString RemoveAction ${LANG_UKRAINIAN} "Видалити"
LangString CloseAction ${LANG_UKRAINIAN} "Закрити"
LangString DowngradeBlocked ${LANG_UKRAINIAN} "Уже встановлено новішу версію SIDEY, тому інсталятор нічого не змінив. Щоб установити ${APP_VERSION}, видаліть поточну версію SIDEY у Параметри Windows > Програми, а потім знову запустіть цей інсталятор."
LangString LegacyMigrationManual ${LANG_UKRAINIAN} "Установлено попередню MSI-версію SIDEY, тому інсталятор нічого не змінив. Видаліть її в Параметри Windows > Програми, а потім знову запустіть цей інсталятор. Не видаляйте файли встановлення SIDEY вручну."
LangString ExistingRemovalFailed ${LANG_UKRAINIAN} "Засіб видалення не завершив роботу: потрібні файли SIDEY можуть бути відсутні або використовуватися. Знову запустіть цей інсталятор і виконайте відновлення, а потім запустіть його ще раз і виберіть видалення. Якщо відновлення завершиться помилкою, перезапустіть Windows і повторіть спробу. Якщо проблема залишиться, зверніться до підтримки та вкажіть код помилки: $0"
LangString PrerequisitesStatus ${LANG_UKRAINIAN} "Перевірка необхідних середовищ виконання. Відсутні компоненти буде завантажено з сайту Microsoft..."
LangString CleanupTitle ${LANG_UKRAINIAN} "Видалення даних користувача SIDEY"
LangString CleanupSubtitle ${LANG_UKRAINIAN} "Виберіть дані поточного користувача для видалення."
LangString CleanupDescription ${LANG_UKRAINIAN} "Застосунок SIDEY буде видалено. Наведені нижче дані збережуться, якщо не позначити їх для видалення."
LangString DeleteLocalData ${LANG_UKRAINIAN} "Видалити налаштування та журнали (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_UKRAINIAN} "Видалити збережені облікові дані для входу в SIDEY"
LangString CleanupFailed ${LANG_UKRAINIAN} "Видалення SIDEY продовжиться, але такі елементи поточного користувача не вдалося видалити. Зазначений код помилки стосується відповідного елемента:$\r$\n$CleanupFailureDetails"
LangString CleanupLocalDataFailure ${LANG_UKRAINIAN} "- Налаштування та журнали (%LOCALAPPDATA%\SIDEY), код помилки: $0"
LangString CleanupCredentialsFailure ${LANG_UKRAINIAN} "- Збережені облікові дані для входу в SIDEY, код помилки: $0"
LangString CleanupStartupFailure ${LANG_UKRAINIAN} "- Запис автозапуску SIDEY, код помилки: $0"
LangString LaunchFailed ${LANG_UKRAINIAN} "SIDEY успішно встановлено, але його не вдалося запустити від імені користувача робочого стола. Перезапустіть Windows і запустіть SIDEY з меню «Пуск». Якщо SIDEY все одно не запускається, зверніться до служби підтримки та вкажіть код помилки: $0"
LangString TransactionFailed ${LANG_UKRAINIAN} "Встановлення SIDEY не завершено. Якщо SIDEY уже було встановлено, попереднє встановлення збережено або відновлено. Код помилки: $0"
LangString TransactionStateUnknown ${LANG_UKRAINIAN} "Інсталятор не зміг підтвердити остаточний стан SIDEY. Перезапустіть Windows і знову запустіть останню версію інсталятора SIDEY. Якщо інсталятор запропонує відновлення, завершіть його. Не видаляйте файли встановлення вручну. Якщо продовжити неможливо, зверніться до служби підтримки та вкажіть код помилки: $0"
LangString TransactionRecoveryFailed ${LANG_UKRAINIAN} "Інсталятору не вдалося відновити перерване встановлення SIDEY. Перезапустіть Windows, а потім знову запустіть останню версію інсталятора SIDEY. Не видаляйте файли встановлення вручну. Якщо проблема не зникне, зверніться до служби підтримки та вкажіть код помилки: $0"
LangString UninstallPreflightFailed ${LANG_UKRAINIAN} "Не вдалося підготувати видалення SIDEY, тому зміни видалення не були розпочаті. Закрийте SIDEY, перезапустіть Windows і повторіть спробу. Якщо проблема не зникне, зверніться до служби підтримки та вкажіть код помилки: $0"
LangString UninstallStateUnknown ${LANG_UKRAINIAN} "Інсталятор не зміг підтвердити остаточний стан видалення SIDEY. Перезапустіть Windows, а потім знову запустіть останню версію інсталятора SIDEY. Не видаляйте файли встановлення вручну. Якщо проблема не зникне, зверніться до служби підтримки та вкажіть код помилки: $0"
LangString SetupAlreadyRunning ${LANG_UKRAINIAN} "Інший інсталятор або засіб видалення SIDEY уже запущено. Закрийте його, перш ніж продовжити."
LangString SetupInitializationFailed ${LANG_UKRAINIAN} "Інсталятору SIDEY не вдалося ініціалізувати блокування встановлення. Перезапустіть Windows і знову запустіть інсталятор. Якщо проблема не зникне, зверніться до служби підтримки та вкажіть код помилки: $1"
LangString CleanupPending ${LANG_UKRAINIAN} "SIDEY установлено, але резервну копію попередньої версії не вдалося видалити. Очищення буде повторено під час наступного запуску інсталятора."
