; SIDEY-specific strings. Standard wizard buttons/pages come from NSIS's NLF files.
LangString LanguageSelectionFailed ${LANG_ENGLISH} "The language selection window could not be opened. Run Setup again."
LangString LanguageSelectionFailed ${LANG_KOREAN} "언어 선택 창을 열지 못했습니다. 설치 프로그램을 다시 실행해 주세요."
LangString LanguageSelectionFailed ${LANG_JAPANESE} "言語選択画面を開けませんでした。セットアップを再実行してください。"
LangString LanguageSelectionFailed ${LANG_SIMPCHINESE} "无法打开语言选择窗口。请重新运行安装程序。"
LangString LanguageSelectionFailed ${LANG_TRADCHINESE} "無法開啟語言選擇視窗。請重新執行安裝程式。"
LangString LanguageSelectionFailed ${LANG_RUSSIAN} "Не удалось открыть окно выбора языка. Запустите программу установки ещё раз."
LangString LanguageSelectionFailed ${LANG_UKRAINIAN} "Не вдалося відкрити вікно вибору мови. Запустіть програму встановлення ще раз."

LangString LaunchSidey ${LANG_JAPANESE} "SIDEY を起動する"
LangString TermsTitle ${LANG_JAPANESE} "SIDEY 利用規約"
LangString TermsSubtitle ${LANG_JAPANESE} "インストールする前に、利用規約を確認して同意してください。"
LangString TermsTop ${LANG_JAPANESE} "以下の利用規約をお読みください。続行するには同意のチェックボックスを選択してください。"
LangString AcceptTerms ${LANG_JAPANESE} "SIDEY の利用規約を読み、同意します。"
LangString MaintenanceTitle ${LANG_JAPANESE} "SIDEY は既にインストールされています"
LangString MaintenanceSubtitle ${LANG_JAPANESE} "実行する操作を選択してください。"
LangString MaintenanceDescription ${LANG_JAPANESE} "同じバージョンの SIDEY がインストールされています。修復またはアンインストールを選択できます。"
LangString RepairAction ${LANG_JAPANESE} "修復"
LangString RemoveAction ${LANG_JAPANESE} "アンインストール"
LangString CloseAction ${LANG_JAPANESE} "閉じる"
LangString DowngradeBlocked ${LANG_JAPANESE} "新しいバージョンの SIDEY が既にインストールされています。${APP_VERSION} をインストールするには、先にアンインストールしてください。"
LangString LegacyMigrationFailed ${LANG_JAPANESE} "以前の SIDEY MSI を削除できないため、インストールを続行できません。エラーコード: $0"
LangString LegacyMigrationRestart ${LANG_JAPANESE} "以前の SIDEY MSI の削除を完了するには、Windows の再起動が必要です。再起動後にセットアップを再実行してください。"
LangString ExistingRemovalFailed ${LANG_JAPANESE} "既存の SIDEY を新しいインストールに向けて準備できませんでした。エラーコード: $0"
LangString PrerequisitesStatus ${LANG_JAPANESE} "必要なランタイムを確認しています。不足している場合は Microsoft からダウンロードします..."
LangString PrerequisitesFailed ${LANG_JAPANESE} "必要なランタイムをインストールできませんでした。インターネット接続を確認し、セットアップを再実行してください。既存の SIDEY は削除されていません。エラーコード: $0"
LangString PrerequisitesRestart ${LANG_JAPANESE} "ランタイムのインストールを完了するには、Windows を再起動してからセットアップを再実行してください。既存の SIDEY は削除されていません。"
LangString CleanupTitle ${LANG_JAPANESE} "SIDEY のユーザーデータの削除"
LangString CleanupSubtitle ${LANG_JAPANESE} "削除する現在のユーザーのデータを選択してください。"
LangString CleanupDescription ${LANG_JAPANESE} "SIDEY アプリをアンインストールします。以下のデータは、選択しない限り保持されます。"
LangString DeleteLocalData ${LANG_JAPANESE} "設定とログを削除する (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_JAPANESE} "保存された SIDEY のログイン情報を削除する"
LangString CleanupFailed ${LANG_JAPANESE} "選択したユーザーデータの一部を削除できませんでした。エラーコード: $0"

LangString LaunchSidey ${LANG_SIMPCHINESE} "启动 SIDEY"
LangString TermsTitle ${LANG_SIMPCHINESE} "SIDEY 使用条款"
LangString TermsSubtitle ${LANG_SIMPCHINESE} "安装 SIDEY 前，请阅读并同意使用条款。"
LangString TermsTop ${LANG_SIMPCHINESE} "请阅读以下条款。勾选同意复选框后才能继续。"
LangString AcceptTerms ${LANG_SIMPCHINESE} "我已阅读并同意 SIDEY 使用条款。"
LangString MaintenanceTitle ${LANG_SIMPCHINESE} "已安装 SIDEY"
LangString MaintenanceSubtitle ${LANG_SIMPCHINESE} "请选择要执行的操作。"
LangString MaintenanceDescription ${LANG_SIMPCHINESE} "已安装相同版本的 SIDEY。您可以修复安装或卸载 SIDEY。"
LangString RepairAction ${LANG_SIMPCHINESE} "修复"
LangString RemoveAction ${LANG_SIMPCHINESE} "卸载"
LangString CloseAction ${LANG_SIMPCHINESE} "关闭"
LangString DowngradeBlocked ${LANG_SIMPCHINESE} "已安装更新版本的 SIDEY。请先将其卸载，再安装 ${APP_VERSION}。"
LangString LegacyMigrationFailed ${LANG_SIMPCHINESE} "无法卸载旧版 SIDEY MSI，安装无法继续。错误代码：$0"
LangString LegacyMigrationRestart ${LANG_SIMPCHINESE} "需要重启 Windows 才能完成旧版 SIDEY MSI 的卸载。请重启后再次运行安装程序。"
LangString ExistingRemovalFailed ${LANG_SIMPCHINESE} "无法清理现有 SIDEY 安装以安装新版本。错误代码：$0"
LangString PrerequisitesStatus ${LANG_SIMPCHINESE} "正在检查所需的运行时；缺少的运行时将从 Microsoft 下载..."
LangString PrerequisitesFailed ${LANG_SIMPCHINESE} "无法安装所需的运行时。请检查网络连接，然后重新运行安装程序。现有 SIDEY 尚未卸载。错误代码：$0"
LangString PrerequisitesRestart ${LANG_SIMPCHINESE} "请重启 Windows 以完成所需运行时的安装，然后重新运行安装程序。现有 SIDEY 尚未卸载。"
LangString CleanupTitle ${LANG_SIMPCHINESE} "选择要删除的 SIDEY 用户数据"
LangString CleanupSubtitle ${LANG_SIMPCHINESE} "请选择要删除的当前用户数据。"
LangString CleanupDescription ${LANG_SIMPCHINESE} "SIDEY 应用将被卸载。以下数据仅在勾选后才会删除。"
LangString DeleteLocalData ${LANG_SIMPCHINESE} "删除设置和日志 (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_SIMPCHINESE} "删除已保存的 SIDEY 登录凭据"
LangString CleanupFailed ${LANG_SIMPCHINESE} "无法删除部分选中的用户数据。错误代码：$0"

LangString LaunchSidey ${LANG_TRADCHINESE} "啟動 SIDEY"
LangString TermsTitle ${LANG_TRADCHINESE} "SIDEY 使用條款"
LangString TermsSubtitle ${LANG_TRADCHINESE} "安裝 SIDEY 前，請閱讀並同意使用條款。"
LangString TermsTop ${LANG_TRADCHINESE} "請閱讀以下條款。勾選同意核取方塊後才能繼續。"
LangString AcceptTerms ${LANG_TRADCHINESE} "我已閱讀並同意 SIDEY 使用條款。"
LangString MaintenanceTitle ${LANG_TRADCHINESE} "已安裝 SIDEY"
LangString MaintenanceSubtitle ${LANG_TRADCHINESE} "請選擇要執行的操作。"
LangString MaintenanceDescription ${LANG_TRADCHINESE} "已安裝相同版本的 SIDEY。您可以修復安裝或解除安裝 SIDEY。"
LangString RepairAction ${LANG_TRADCHINESE} "修復"
LangString RemoveAction ${LANG_TRADCHINESE} "解除安裝"
LangString CloseAction ${LANG_TRADCHINESE} "關閉"
LangString DowngradeBlocked ${LANG_TRADCHINESE} "已安裝較新版本的 SIDEY。請先將其解除安裝，再安裝 ${APP_VERSION}。"
LangString LegacyMigrationFailed ${LANG_TRADCHINESE} "無法解除安裝舊版 SIDEY MSI，安裝無法繼續。錯誤代碼：$0"
LangString LegacyMigrationRestart ${LANG_TRADCHINESE} "必須重新啟動 Windows 才能完成舊版 SIDEY MSI 的解除安裝。請重新啟動後再次執行安裝程式。"
LangString ExistingRemovalFailed ${LANG_TRADCHINESE} "無法清理現有 SIDEY 安裝以安裝新版本。錯誤代碼：$0"
LangString PrerequisitesStatus ${LANG_TRADCHINESE} "正在檢查所需的執行階段；缺少的執行階段將從 Microsoft 下載..."
LangString PrerequisitesFailed ${LANG_TRADCHINESE} "無法安裝所需的執行階段。請檢查網路連線，然後重新執行安裝程式。現有 SIDEY 尚未解除安裝。錯誤代碼：$0"
LangString PrerequisitesRestart ${LANG_TRADCHINESE} "請重新啟動 Windows 以完成所需執行階段的安裝，然後重新執行安裝程式。現有 SIDEY 尚未解除安裝。"
LangString CleanupTitle ${LANG_TRADCHINESE} "選擇要刪除的 SIDEY 使用者資料"
LangString CleanupSubtitle ${LANG_TRADCHINESE} "請選擇要刪除的目前使用者資料。"
LangString CleanupDescription ${LANG_TRADCHINESE} "SIDEY 應用程式將被解除安裝。以下資料只有在勾選後才會刪除。"
LangString DeleteLocalData ${LANG_TRADCHINESE} "刪除設定和記錄 (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_TRADCHINESE} "刪除已儲存的 SIDEY 登入認證"
LangString CleanupFailed ${LANG_TRADCHINESE} "無法刪除部分選取的使用者資料。錯誤代碼：$0"

LangString LaunchSidey ${LANG_RUSSIAN} "Запустить SIDEY"
LangString TermsTitle ${LANG_RUSSIAN} "Условия использования SIDEY"
LangString TermsSubtitle ${LANG_RUSSIAN} "Перед установкой ознакомьтесь с условиями и примите их."
LangString TermsTop ${LANG_RUSSIAN} "Прочитайте условия ниже. Чтобы продолжить, установите флажок согласия."
LangString AcceptTerms ${LANG_RUSSIAN} "Я прочитал(а) и принимаю условия использования SIDEY."
LangString MaintenanceTitle ${LANG_RUSSIAN} "SIDEY уже установлен"
LangString MaintenanceSubtitle ${LANG_RUSSIAN} "Выберите нужное действие."
LangString MaintenanceDescription ${LANG_RUSSIAN} "Эта версия SIDEY уже установлена. Вы можете восстановить или удалить приложение."
LangString RepairAction ${LANG_RUSSIAN} "Восстановить"
LangString RemoveAction ${LANG_RUSSIAN} "Удалить"
LangString CloseAction ${LANG_RUSSIAN} "Закрыть"
LangString DowngradeBlocked ${LANG_RUSSIAN} "Уже установлена более новая версия SIDEY. Удалите её перед установкой ${APP_VERSION}."
LangString LegacyMigrationFailed ${LANG_RUSSIAN} "Не удалось удалить предыдущую MSI-версию SIDEY. Установка не может быть продолжена. Код ошибки: $0"
LangString LegacyMigrationRestart ${LANG_RUSSIAN} "Для завершения удаления предыдущей MSI-версии SIDEY требуется перезагрузка Windows. После перезагрузки запустите установку снова."
LangString ExistingRemovalFailed ${LANG_RUSSIAN} "Не удалось подготовить существующую установку SIDEY к замене. Код ошибки: $0"
LangString PrerequisitesStatus ${LANG_RUSSIAN} "Проверка необходимых сред выполнения. Недостающие компоненты будут загружены с сайта Microsoft..."
LangString PrerequisitesFailed ${LANG_RUSSIAN} "Не удалось установить необходимые среды выполнения. Проверьте подключение к интернету и повторите установку. Существующая установка SIDEY не удалена. Код ошибки: $0"
LangString PrerequisitesRestart ${LANG_RUSSIAN} "Перезагрузите Windows для завершения установки сред выполнения, затем запустите установку снова. Существующая установка SIDEY не удалена."
LangString CleanupTitle ${LANG_RUSSIAN} "Удаление пользовательских данных SIDEY"
LangString CleanupSubtitle ${LANG_RUSSIAN} "Выберите данные текущего пользователя для удаления."
LangString CleanupDescription ${LANG_RUSSIAN} "Приложение SIDEY будет удалено. Данные ниже сохранятся, если не отметить их для удаления."
LangString DeleteLocalData ${LANG_RUSSIAN} "Удалить настройки и журналы (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_RUSSIAN} "Удалить сохранённые учётные данные для входа в SIDEY"
LangString CleanupFailed ${LANG_RUSSIAN} "Не удалось удалить часть выбранных пользовательских данных. Код ошибки: $0"

LangString LaunchSidey ${LANG_UKRAINIAN} "Запустити SIDEY"
LangString TermsTitle ${LANG_UKRAINIAN} "Умови використання SIDEY"
LangString TermsSubtitle ${LANG_UKRAINIAN} "Перед встановленням ознайомтеся з умовами та прийміть їх."
LangString TermsTop ${LANG_UKRAINIAN} "Прочитайте умови нижче. Щоб продовжити, установіть прапорець згоди."
LangString AcceptTerms ${LANG_UKRAINIAN} "Я прочитав(-ла) та приймаю умови використання SIDEY."
LangString MaintenanceTitle ${LANG_UKRAINIAN} "SIDEY уже встановлено"
LangString MaintenanceSubtitle ${LANG_UKRAINIAN} "Виберіть потрібну дію."
LangString MaintenanceDescription ${LANG_UKRAINIAN} "Цю версію SIDEY уже встановлено. Ви можете відновити або видалити застосунок."
LangString RepairAction ${LANG_UKRAINIAN} "Відновити"
LangString RemoveAction ${LANG_UKRAINIAN} "Видалити"
LangString CloseAction ${LANG_UKRAINIAN} "Закрити"
LangString DowngradeBlocked ${LANG_UKRAINIAN} "Уже встановлено новішу версію SIDEY. Видаліть її перед встановленням ${APP_VERSION}."
LangString LegacyMigrationFailed ${LANG_UKRAINIAN} "Не вдалося видалити попередню MSI-версію SIDEY. Встановлення не може бути продовжено. Код помилки: $0"
LangString LegacyMigrationRestart ${LANG_UKRAINIAN} "Для завершення видалення попередньої MSI-версії SIDEY потрібно перезапустити Windows. Після перезапуску запустіть встановлення знову."
LangString ExistingRemovalFailed ${LANG_UKRAINIAN} "Не вдалося підготувати наявне встановлення SIDEY до заміни. Код помилки: $0"
LangString PrerequisitesStatus ${LANG_UKRAINIAN} "Перевірка необхідних середовищ виконання. Відсутні компоненти буде завантажено з сайту Microsoft..."
LangString PrerequisitesFailed ${LANG_UKRAINIAN} "Не вдалося встановити необхідні середовища виконання. Перевірте з’єднання з інтернетом і повторіть встановлення. Наявне встановлення SIDEY не видалено. Код помилки: $0"
LangString PrerequisitesRestart ${LANG_UKRAINIAN} "Перезапустіть Windows, щоб завершити встановлення середовищ виконання, а потім запустіть встановлення знову. Наявне встановлення SIDEY не видалено."
LangString CleanupTitle ${LANG_UKRAINIAN} "Видалення даних користувача SIDEY"
LangString CleanupSubtitle ${LANG_UKRAINIAN} "Виберіть дані поточного користувача для видалення."
LangString CleanupDescription ${LANG_UKRAINIAN} "Застосунок SIDEY буде видалено. Наведені нижче дані збережуться, якщо не позначити їх для видалення."
LangString DeleteLocalData ${LANG_UKRAINIAN} "Видалити налаштування та журнали (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_UKRAINIAN} "Видалити збережені облікові дані для входу в SIDEY"
LangString CleanupFailed ${LANG_UKRAINIAN} "Не вдалося видалити частину вибраних даних користувача. Код помилки: $0"
