#!/usr/bin/env python

env = SConscript("../godot-cpp/SConstruct", {"api_version": "4.7"})

env.Append(CPPPATH=["src"])
env.Append(CXXFLAGS=["-std=c++17", "-fobjc-arc", "-mmacosx-version-min=13.0"])
env.Append(LINKFLAGS=[
    "-mmacosx-version-min=13.0",
    "-framework", "AppKit",
    "-framework", "ApplicationServices",
    "-framework", "Carbon",
    "-framework", "Security",
    "-framework", "ServiceManagement",
])

sources = Glob("src/*.cpp") + Glob("src/*.mm")
library = env.SharedLibrary(
    "bin/libsidey_macos{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

env.NoCache(library)
Default(library)
