name: 📗 문서 수정
description: Tell us if there is missing or incorrect documentation
labels: 
  - documentation
body:
  - type: markdown
    attributes:
      value: |
        새 이슈를 등록하기 전에, 이미 비슷한 문서 수정이 보고되었는지 기존 이슈를 먼저 검색해 주세요.
        이미 등록된 이슈가 있다면, 새로 이슈를 만드는 대신 기존 이슈에 👍 리액션을 남겨주세요. (댓글은 작성하지 않으셔도 돼요!)

  - type: dropdown
    attributes:
      label: 어떤 종류의 문제인가요?
      multiple: true
      options:
        - 내용이 누락됨
        - 내용이 잘못됨
        - 이해하기 어려움
        - 기타
  - type: textarea
    attributes:
      label: 어떤 문제가 있나요?
    validations:
      required: true
  - type: textarea
    attributes:
      label: 어디서 해당 문제를 발견하셨나요?
      description: 가능한 경우 문제를 발견한 문서의 URL을 남겨주세요.
