#!/usr/bin/env python3
"""Generate only the selected platform's catalog mirrors; --check never writes."""
from __future__ import annotations
import argparse
from decimal import Decimal
import json
from pathlib import Path
import re
import sys
from workflow import branch, validate_paths

ROOT = Path(__file__).resolve().parents[1]
CATALOG = 'assets/v1/commerce-catalog.json'


def validate(catalog, manifest):
    ids, items, apple_ids = set(), set(), set()
    assets = {kind: {asset['id'] for asset in manifest[kind + 's']} for kind in ('character', 'throwable', 'bubble')}
    by_id = {entry['id']: entry for entry in catalog}
    for entry in catalog:
        for key in ('id', 'item_id', 'app_store_product_id'):
            if not re.fullmatch(r'[a-z][a-z0-9_]*', entry[key]):
                raise ValueError(f'Invalid {key}: {entry[key]}')
        if entry['id'] in ids or entry['entitlement'] in items:
            raise ValueError(f'Duplicate product or entitlement: {entry["id"]}')
        ids.add(entry['id']); items.add(entry['entitlement'])
        kind = entry['kind']
        if kind not in assets or (entry.get('render_asset_id') or entry['item_id']) not in assets[kind]:
            raise ValueError(f'Unknown render asset: {entry["id"]}')
        if entry['entitlement'] != f'{kind}:{entry["item_id"]}':
            raise ValueError(f'Entitlement differs from catalog item: {entry["id"]}')
        for price in ('direct_price', 'app_store_price'):
            if type(entry[price]) is not int or entry[price] <= 0:
                raise ValueError(f'Invalid price: {entry["id"]}')
        for apple_id in [entry['app_store_product_id'], *entry['legacy_app_store_product_ids']]:
            if not re.fullmatch(r'[a-z][a-z0-9_]*', apple_id) or apple_id in apple_ids:
                raise ValueError(f'Duplicate or invalid Apple ID: {apple_id}')
            apple_ids.add(apple_id)
        related = entry.get('related_character_product_id')
        if related and (kind != 'throwable' or by_id.get(related, {}).get('kind') != 'character'):
            raise ValueError(f'Invalid keepsake relationship: {entry["id"]}')
    return catalog


def generated(catalog, target):
    if target == 'macos':
        return {'macos/SIDEY/Resources/Commerce/commerce-catalog.json': (ROOT / CATALOG).read_bytes()}
    offers = {apple: entry['entitlement'] for entry in catalog
              for apple in [entry['app_store_product_id'], *entry['legacy_app_store_product_ids']]}
    header = '// Generated by scripts/commerce_catalog.py --target shared. Do not edit.\n'
    browser = {}
    for entry in catalog:
        kind = entry['kind']
        render = entry.get('render_asset_id') or entry['item_id']
        image = f'assets/cosmetics/{render}.png' if kind == 'bubble' else f'assets/store/{render}.png'
        browser[entry['id']] = {'name': entry['name'], 'image': image,
            'kind': 'effect' if entry['id'] == 'throwable_toy_cannon' else kind,
            'asset': f'assets/cosmetics/{render}_decoration.png' if kind == 'bubble' else image,
            'mode': 'cannon' if entry['id'] == 'throwable_toy_cannon' else kind}
    return {
        'services/app-store-verifier/src/product-entitlements.ts':
            (header + 'export const entitlementByProduct = Object.freeze(' + json.dumps(offers, indent=2) + ' as const);\n').encode(),
        'supabase/functions/_shared/commerce-products.ts':
            (header + 'export const SUPPORTED_PRODUCT_IDS = new Set(' + json.dumps([e['id'] for e in catalog], indent=2) + ');\n').encode(),
        'website/public/assets/commerce-products.js':
            (header + 'export const commerceProducts = Object.freeze(' + json.dumps(browser, ensure_ascii=False, indent=2) + ');\n').encode(),
    }


def check_storekit(catalog, configuration):
    products = configuration['products']
    ids = [p['productID'] for p in products]
    if len(ids) != len(set(ids)):
        raise ValueError('Duplicate StoreKit product ID')
    known = {apple for entry in catalog for apple in [entry['app_store_product_id'], *entry['legacy_app_store_product_ids']]}
    if not set(ids) <= known:
        raise ValueError('StoreKit contains unknown product IDs')
    for entry in catalog:
        product = next((p for p in products if p['productID'] == entry['app_store_product_id']), None)
        if not product or product['type'] != 'NonConsumable' or Decimal(product['displayPrice']) != entry['app_store_price']:
            raise ValueError(f'StoreKit ID/type/price differs: {entry["id"]}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--target', required=True, choices=['shared', 'macos'])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = parser.parse_args()
    catalog = validate(json.loads((ROOT / CATALOG).read_text()), json.loads((ROOT / 'assets/v1/manifest.json').read_text()))
    output = generated(catalog, args.target)
    if args.write:
        validate_paths(branch(ROOT), output)
    for name, data in output.items():
        path = ROOT / name
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        elif not path.exists() or path.read_bytes() != data:
            raise ValueError(f'Generated catalog differs: {name}; regenerate only --target {args.target}')
    if args.target == 'macos':
        check_storekit(catalog, json.loads((ROOT / 'macos/SIDEYAppStore.storekit').read_text()))
    print(f'{args.target}: {len(catalog)} products and {len(output)} mirrors verified')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, KeyError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
