#!/usr/bin/env python3
"""Generate or verify one platform's commerce catalog mirrors."""

from __future__ import annotations

import argparse
from decimal import Decimal
import json
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent / "skills"))

from catalog_source import SOURCES, load_source  # noqa: E402
from sidey_tools.repository import branch, validate_paths  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
CATALOG = "assets/v1/commerce-catalog.json"
MANIFEST = "assets/v1/manifest.json"
STOREKIT_CONFIGURATION = "macos/SIDEYAppStore.storekit"


def read_json(path: Path):
    """Read a UTF-8 JSON document."""

    return json.loads(path.read_text(encoding="utf-8"))


def asset_ids_by_kind(manifest):
    """Index manifest asset identifiers by commerce item kind."""

    kinds = ("character", "throwable", "bubble")
    return {
        kind: {asset["id"] for asset in manifest[f"{kind}s"]}
        for kind in kinds
    }


def validate_identifiers(entry):
    """Validate the machine-readable identifiers for one product."""

    for key in ("id", "item_id", "app_store_product_id"):
        if not re.fullmatch(r"[a-z][a-z0-9_]*", entry[key]):
            raise ValueError(f"Invalid {key}: {entry[key]}")


def validate_apple_ids(entry, known_apple_ids):
    """Validate and record the current and legacy App Store identifiers."""

    apple_ids = [
        entry["app_store_product_id"],
        *entry["legacy_app_store_product_ids"],
    ]
    for apple_id in apple_ids:
        valid = re.fullmatch(r"[a-z][a-z0-9_]*", apple_id)
        if not valid or apple_id in known_apple_ids:
            raise ValueError(f"Duplicate or invalid Apple ID: {apple_id}")
        known_apple_ids.add(apple_id)


def validate_relationship(entry, products_by_id):
    """Validate an optional throwable-to-character relationship."""

    related = entry.get("related_character_product_id")
    related_kind = products_by_id.get(related, {}).get("kind")
    if related and (
        entry["kind"] != "throwable" or related_kind != "character"
    ):
        raise ValueError(f"Invalid keepsake relationship: {entry['id']}")


def validate(catalog, manifest):
    """Validate the canonical catalog against the asset manifest."""

    product_ids = set()
    entitlements = set()
    apple_ids = set()
    assets = asset_ids_by_kind(manifest)
    products_by_id = {entry["id"]: entry for entry in catalog}

    for entry in catalog:
        validate_identifiers(entry)

        if (
            entry["id"] in product_ids
            or entry["entitlement"] in entitlements
        ):
            raise ValueError(
                f"Duplicate product or entitlement: {entry['id']}"
            )
        product_ids.add(entry["id"])
        entitlements.add(entry["entitlement"])

        kind = entry["kind"]
        render_asset = entry.get("render_asset_id") or entry["item_id"]
        if kind not in assets or render_asset not in assets[kind]:
            raise ValueError(f"Unknown render asset: {entry['id']}")

        expected_entitlement = f"{kind}:{entry['item_id']}"
        if entry["entitlement"] != expected_entitlement:
            raise ValueError(
                f"Entitlement differs from catalog item: {entry['id']}"
            )

        for price_name in ("direct_price", "app_store_price"):
            price = entry[price_name]
            if type(price) is not int or price <= 0:
                raise ValueError(f"Invalid price: {entry['id']}")

        validate_apple_ids(entry, apple_ids)
        validate_relationship(entry, products_by_id)

    return catalog


def macos_output(catalog):
    """Return the native commerce catalog mirror."""

    data = json.dumps(catalog, ensure_ascii=False, indent=2) + "\n"
    return {
        "macos/SIDEY/Resources/Commerce/commerce-catalog.json": (
            data.encode()
        )
    }


def browser_product(entry):
    """Convert one canonical entry into the public website shape."""

    kind = entry["kind"]
    render_asset = entry.get("render_asset_id") or entry["item_id"]
    if kind == "bubble":
        image = f"assets/cosmetics/{render_asset}.png"
        asset = f"assets/cosmetics/{render_asset}_decoration.png"
    else:
        image = f"assets/store/{render_asset}.png"
        asset = image

    is_cannon = entry["id"] == "throwable_toy_cannon"
    return {
        "name": entry["name"],
        "image": image,
        "kind": "effect" if is_cannon else kind,
        "asset": asset,
        "mode": "cannon" if is_cannon else kind,
    }


def shared_output(catalog):
    """Return the generated public website module."""

    header = (
        "// Generated by scripts/commerce_catalog.py --target shared. "
        "Do not edit.\n"
    )
    products = {
        entry["id"]: browser_product(entry)
        for entry in catalog
    }
    module = (
        header
        + "export const commerceProducts = Object.freeze("
        + json.dumps(products, ensure_ascii=False, indent=2)
        + ");\n"
    )
    return {
        "website/public/assets/commerce-products.js": module.encode()
    }


def generated(catalog, target):
    """Return the generated files for *target*."""

    return macos_output(catalog) if target == "macos" else shared_output(
        catalog
    )


def check_storekit(catalog, configuration):
    """Verify the StoreKit configuration against the pinned catalog."""

    products = configuration["products"]
    product_ids = [product["productID"] for product in products]
    if len(product_ids) != len(set(product_ids)):
        raise ValueError("Duplicate StoreKit product ID")

    known_ids = {
        apple_id
        for entry in catalog
        for apple_id in [
            entry["app_store_product_id"],
            *entry["legacy_app_store_product_ids"],
        ]
    }
    if not set(product_ids) <= known_ids:
        raise ValueError("StoreKit contains unknown product IDs")

    products_by_id = {
        product["productID"]: product for product in products
    }
    for entry in catalog:
        product = products_by_id.get(entry["app_store_product_id"])
        valid = (
            product
            and product["type"] == "NonConsumable"
            and Decimal(product["displayPrice"])
            == entry["app_store_price"]
        )
        if not valid:
            raise ValueError(
                f"StoreKit ID/type/price differs: {entry['id']}"
            )


def parse_args(argv=None):
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--target",
        required=True,
        choices=["shared", "macos"],
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument(
        "--source-commit",
        help="Reviewed full source SHA (required for native writes)",
    )
    args = parser.parse_args(argv)

    if args.target == "macos" and args.write and not args.source_commit:
        parser.error("native writes require --source-commit")
    if args.target == "shared" and args.source_commit:
        parser.error("--source-commit is only for native mirrors")
    return args


def load_catalog(target, source_commit):
    """Load the canonical or reviewed native source catalog."""

    catalog = read_json(ROOT / CATALOG)
    manifest = read_json(ROOT / MANIFEST)
    validate(catalog, manifest)

    if target != "macos":
        return catalog, None

    catalog, manifest, metadata = load_source(
        ROOT,
        "macos",
        source_commit,
    )
    validate(catalog, manifest)
    return catalog, metadata


def write_or_check(outputs, target, write):
    """Write generated files or verify their checked-in contents."""

    for name, data in outputs.items():
        path = ROOT / name
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        elif not path.exists() or path.read_bytes() != data:
            raise ValueError(
                f"Generated catalog differs: {name}; regenerate only "
                f"--target {target}"
            )


def main(argv=None):
    """Generate or verify the selected target."""

    args = parse_args(argv)
    catalog, metadata = load_catalog(args.target, args.source_commit)
    outputs = generated(catalog, args.target)
    if metadata is not None:
        data = json.dumps(metadata, indent=2) + "\n"
        outputs[SOURCES["macos"]] = data.encode()

    if args.write:
        validate_paths(branch(ROOT), list(outputs))
    write_or_check(outputs, args.target, args.write)

    if args.target == "macos":
        check_storekit(catalog, read_json(ROOT / STOREKIT_CONFIGURATION))
    print(
        f"{args.target}: {len(catalog)} products and "
        f"{len(outputs)} mirrors verified"
    )


if __name__ == "__main__":
    try:
        main()
    except (ValueError, KeyError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
